// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mi_proyecto_sena.Data;

#nullable disable

namespace mi_proyecto_sena.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251028135353_Migrations_001")]
    partial class Migrations_001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mi_proyecto_sena.Models.usuarioModel", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Usuario_Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("User_Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
